pub mod antigravity;
pub mod claude_code;
mod claude_code_history;
pub mod cline;
pub mod codex_cli;
pub mod copilot;
pub mod copilot_cli;
pub mod deepseek_harness;
pub mod gemini_cli;
pub mod grok;
pub mod kilo_cli;
pub mod kilo_code;
pub mod opencode;
pub(crate) mod opencode_common;
pub mod pi_agent;
pub mod piebald;
pub mod qwen_code;
pub mod roo_code;
pub mod zoo_code;

pub use antigravity::AntigravityCliAnalyzer;
pub use claude_code::ClaudeCodeAnalyzer;
pub use cline::ClineAnalyzer;
pub use codex_cli::CodexCliAnalyzer;
pub use copilot::CopilotAnalyzer;
pub use copilot_cli::CopilotCliAnalyzer;
pub use deepseek_harness::DeepSeekHarnessAnalyzer;
pub use gemini_cli::GeminiCliAnalyzer;
pub use grok::GrokAnalyzer;
pub use kilo_cli::KiloCliAnalyzer;
pub use kilo_code::KiloCodeAnalyzer;
pub use opencode::OpenCodeAnalyzer;
pub use pi_agent::PiAgentAnalyzer;
pub use piebald::PiebaldAnalyzer;
pub use qwen_code::QwenCodeAnalyzer;
pub use roo_code::RooCodeAnalyzer;
pub use zoo_code::ZooCodeAnalyzer;

#[cfg(test)]
pub mod tests;
